"""Optional integrations: systemd user timer and desktop notifications."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from quiver import paths
from quiver.config import Config
from quiver.errors import AimError

SERVICE_NAME = "quiver-check"
TIMER_UNIT = f"{SERVICE_NAME}.timer"
SERVICE_UNIT = f"{SERVICE_NAME}.service"

SERVICE_TEMPLATE = """# Generated by `quiver timer install`
[Unit]
Description=quiver - check AppImages for available updates

[Service]
Type=oneshot
ExecStart={aim_bin} check-all --notify
"""

TIMER_TEMPLATE = """# Generated by `quiver timer install`
[Unit]
Description=quiver - periodic AppImage update checks

[Timer]
OnCalendar={on_calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""


def notify(title: str, body: str) -> bool:
    """Send a desktop notification if notify-send exists. Best-effort."""
    binary = shutil.which("notify-send")
    if not binary:
        return False
    try:
        subprocess.run(
            [binary, "-a", "quiver", title, body],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=10,
            check=False,
        )
        return True
    except (OSError, subprocess.TimeoutExpired):
        return False


def _unit_dir() -> Path:
    return paths.config_home() / "systemd" / "user"


def _systemctl(*args: str) -> subprocess.CompletedProcess:
    binary = shutil.which("systemctl")
    if binary is None:
        raise AimError("systemctl not found", hint="Systemd is required for timer management.")
    return subprocess.run(
        [binary, "--user", *args],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )


def install_timer(_cfg: Config, *, on_calendar: str = "daily", enable: bool = True) -> Path:
    aim_bin = shutil.which("quiver")
    if aim_bin is None:
        raise AimError(
            "the `quiver` command was not found on PATH",
            hint="Install the tool first (uv tool install), then re-run `quiver timer install`.",
        )
    unit_dir = _unit_dir()
    unit_dir.mkdir(parents=True, exist_ok=True)
    service = unit_dir / SERVICE_UNIT
    timer = unit_dir / TIMER_UNIT
    service.write_text(SERVICE_TEMPLATE.format(aim_bin=aim_bin), encoding="utf-8")
    timer.write_text(TIMER_TEMPLATE.format(on_calendar=on_calendar), encoding="utf-8")
    if enable:
        proc = _systemctl("daemon-reload")
        if proc.returncode != 0:
            raise AimError(f"systemctl --user daemon-reload failed: {proc.stderr.strip()}")
        proc = _systemctl("enable", "--now", TIMER_UNIT)
        if proc.returncode != 0:
            raise AimError(f"could not enable timer: {proc.stderr.strip()}")
    return timer


def uninstall_timer() -> bool:
    _systemctl("disable", "--now", TIMER_UNIT)
    removed = False
    for unit in (_unit_dir() / TIMER_UNIT, _unit_dir() / SERVICE_UNIT):
        if unit.exists():
            unit.unlink()
            removed = True
    _systemctl("daemon-reload")
    return removed


def timer_status() -> str:
    proc = _systemctl("is-active", TIMER_UNIT)
    return proc.stdout.strip() or proc.stderr.strip() or "unknown"
